[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["@upstash/redis"]

[build.environment]
  MICROSOFT_CLIENT_SECRET = "placeholder-create-real-secret-in-azure"
  MICROSOFT_CLIENT_ID = "eabd0e31-5707-4a85-aae6-79c53dc2c7f0"
  MICROSOFT_TENANT_ID = "common"
  UPSTASH_REDIS_REST_URL = "placeholder-optional-redis-url"
  UPSTASH_REDIS_REST_TOKEN = "placeholder-optional-redis-token"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[dev]
  command = "npm run dev"
  port = 8888