[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[functions]
  directory = "netlify/functions"
  # If you use any npm packages in your functions, list them below:
  external_node_modules = ["node-fetch", "axios", "telegraf"] # <-- Edit to match your dependencies
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 8888
  publish = "dist"

# Troubleshooting:
# - Ensure your function files are in netlify/functions (e.g., netlify/functions/sendTelegram.js)
# - If you use TypeScript, your build step must transpile .ts to .js in netlify/functions
# - If you add new dependencies, redeploy to ensure they are bundled